name: Test and build

on: [pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'ubuntu-20.04']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Dependencies (Linux)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y devscripts debhelper moreutils fakeroot jq pigz help2man
        wget "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz"
        tar --xz -xvf "shellcheck-stable.linux.x86_64.tar.xz"
        sudo cp shellcheck-stable/shellcheck /usr/bin/shellcheck
    - name: Get Sources
      uses: actions/checkout@v4
    - name: Test
      run: |
        export PATH="$PATH:/snap/bin"
        make test
      shell: bash
    - name: Build (Linux)
      run: DEB_BUILD_OPTIONS=nocheck debuild -us -uc
